### ISSUE TITLE
TypeError: create_connection() got an unexpected keyword argument 'local_addr'

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#227]
Noticed this in logs after updating to 1.0.16:

Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]: INFO:PeerManager:beginning peer discovery; force use of proxy: False
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]: INFO:PeerManager:wrote out 5 peers
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]: ERROR:Controller:Traceback (most recent call last):
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.16-py3.6.egg/server/controller.py", line 157, in on_future_done
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:     future.result()
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.16-py3.6.egg/server/peers.py", line 516, in main_loop
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:     await self.retry_peers()
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.16-py3.6.egg/server/peers.py", line 549, in retry_peers
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:     self.retry_peer(peer, pairs)
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.16-py3.6.egg/server/peers.py", line 567, in retry_peer
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]:     coro = create_connection(protocol_factory, peer.host, port, ssl=sslc, local_addr=local_addr)
Aug 21 06:49:28 hsmiths-ubuntu electrumx_server.py[7682]: TypeError: create_connection() got an unexpected keyword argument 'local_addr'
Aug 21 06:49:29 hsmiths-ubuntu electrumx_server.py[7682]: INFO:ElectrumX:[0] SSL 192.168.69.1:40950, 1 total
Aug 21 06:49:29 hsmiths-ubuntu electrumx_server.py[7682]: INFO:PeerManager:accepted new peer 1/1 he36kyperp3kbuxu.onion from testnet.hsmiths.com
Aug 21 06:49:29 hsmiths-ubuntu electrumx_server.py[7682]: INFO:PeerManager:verified testnet.hsmiths.com via SSL at 76.174.26.91 in 0.3s
