### ISSUE TITLE
getinfo not working in version 1.8.10: 'LocalRPC' object has no attribute 'can_send'

### ISSUE THREAD

**Issue by freerko** [kyuupichan/electrumx#634]
On Bitcoin (not Cash), after the upgrade to ElectrumX 1.8.10 and aiorpcx-0.10.0 the "electrumx_rpc getinfo" is not working anymore, just printing:

> hostname:~# electrumx_rpc getinfo
error making request: RPCError(-32603, 'internal server error')

In the logfile:

> Nov 05 22:16:05 hostname electrumx_server[29317]: ERROR:LocalRPC:[0] exception handling Request('getinfo', {})
Nov 05 22:16:05 hostname electrumx_server[29317]: Traceback (most recent call last):
Nov 05 22:16:05 hostname electrumx_server[29317]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/session.py", line 456, in _throttled_request
Nov 05 22:16:05 hostname electrumx_server[29317]:     result = await self.handle_request(request)
Nov 05 22:16:05 hostname electrumx_server[29317]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.10-py3.7.egg/electrumx/server/session.py", line 696, in handle_request
Nov 05 22:16:05 hostname electrumx_server[29317]:     return await coro
Nov 05 22:16:05 hostname electrumx_server[29317]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.10-py3.7.egg/electrumx/server/session.py", line 402, in rpc_getinfo
Nov 05 22:16:05 hostname electrumx_server[29317]:     return self._get_info()
Nov 05 22:16:05 hostname electrumx_server[29317]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.10-py3.7.egg/electrumx/server/session.py", line 291, in _get_info
Nov 05 22:16:05 hostname electrumx_server[29317]:     'paused': sum(not s.can_send.is_set() for s in self.sessions),
Nov 05 22:16:05 hostname electrumx_server[29317]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.8.10-py3.7.egg/electrumx/server/session.py", line 291, in <genexpr>
Nov 05 22:16:05 hostname electrumx_server[29317]:     'paused': sum(not s.can_send.is_set() for s in self.sessions),
Nov 05 22:16:05 hostname electrumx_server[29317]: AttributeError: 'LocalRPC' object has no attribute 'can_send'

**Comment by kyuupichan** [comment]
Yeah sorry about that; should be good in git HEAD
